use_frameworks!

platform :ios, '9.0'

target 'SynECG_Example' do
  pod 'SynECG', :path => '../'

  target 'SynECG_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
